import { sdk } from './sdk'
import {
  grpcHostId,
  grpcInterfaceId,
  networkPorts,
  peerHostId,
  peerInterfaceId,
  rpcHostId,
  rpcInterfaceId,
  rpcPlaintextHostId,
  rpcPlaintextInterfaceId,
  rpcPlaintextPort,
  Network,
  NETWORKS,
} from './utils'
import { bchdConf } from './fileModels/bchd.conf'
import { storeJson } from './fileModels/store.json'

export const setInterfaces = sdk.setupInterfaces(async ({ effects }) => {
  const conf = await bchdConf.read().const(effects)
  const store = await storeJson.read().const(effects)
  const network: Network =
    NETWORKS.includes(store?.network as Network) ? (store!.network as Network) : 'mainnet'
  const { rpc: rpcPort, peer: peerPort, grpc: grpcPort } = networkPorts[network]
  const receipts = []

  // ── RPC ──────────────────────────────────────────────────────────────
  // BCHD's RPC server is JSON-RPC-over-HTTPS. We enable native TLS (cert
  // from `gencerts` in the nocow oneshot) so that BCHD does not emit the
  // `--notls option is not recommended when binding RPC to non localhost`
  // advisory at every startup. Declared as pass-through TLS so StartOS
  // forwards raw TLS to the backend and hands clients an https:// URL.
  // Clients must trust the self-signed cert (or skip verification).
  const rpcMulti = sdk.MultiHost.of(effects, rpcHostId)
  const rpcOrigin = await rpcMulti.bindPort(rpcPort, {
    protocol: null,
    preferredExternalPort: rpcPort,
    addSsl: null,
    secure: { ssl: true },
  })
  const rpc = sdk.createInterface(effects, {
    name: 'RPC Interface',
    id: rpcInterfaceId,
    description: 'Listens for JSON-RPC commands over TLS',
    type: 'api',
    masked: false,
    schemeOverride: { ssl: 'https', noSsl: 'https' },
    username: null,
    path: '',
    query: {},
  })
  receipts.push(await rpcOrigin.export([rpc]))

  // ── P2P ──────────────────────────────────────────────────────────────
  const peerMulti = sdk.MultiHost.of(effects, peerHostId)
  const peerOrigin = await peerMulti.bindPort(peerPort, {
    protocol: null,
    preferredExternalPort: peerPort,
    addSsl: null,
    secure: { ssl: false },
  })
  const peer = sdk.createInterface(effects, {
    name: 'Peer Interface',
    id: peerInterfaceId,
    description: 'Listens for incoming connections from peers on the bitcoin cash network',
    type: 'p2p',
    masked: false,
    schemeOverride: { ssl: null, noSsl: null },
    username: null,
    path: '',
    query: {},
  })
  receipts.push(await peerOrigin.export([peer]))

  // ── gRPC (conditional) ──────────────────────────────────────────────
  // BCHD's gRPC listener always serves native TLS (HTTP/2 over TLS) using the
  // self-signed cert generated by `gencerts` — there is no flag to disable it.
  // Declaring the bound port as `protocol: 'http'` caused the StartOS reverse
  // proxy to HTTP-probe the backend every ~30s, producing continuous
  // `http: TLS handshake error from 127.0.0.1:<port>: EOF` log noise and
  // breaking gRPC forwarding through the proxy. We instead declare the bind
  // as a pass-through TLS backend so StartOS forwards raw TLS to bchd.
  const grpcEnabled = (conf?.grpclisten ?? '') !== ''
  if (grpcEnabled) {
    const grpcMulti = sdk.MultiHost.of(effects, grpcHostId)
    const grpcOrigin = await grpcMulti.bindPort(grpcPort, {
      protocol: null,
      preferredExternalPort: grpcPort,
      addSsl: null,
      secure: { ssl: true },
    })
    const grpc = sdk.createInterface(effects, {
      name: 'gRPC Interface',
      id: grpcInterfaceId,
      description:
        'BCHD-specific gRPC API over TLS for compact block filters and pub/sub notifications',
      type: 'api',
      masked: false,
      schemeOverride: { ssl: 'https', noSsl: 'https' },
      username: null,
      path: '',
      query: {},
    })
    receipts.push(await grpcOrigin.export([grpc]))
  }

  // ── RPC Plaintext Proxy (stunnel sidecar for ckpool-lineage miners) ──
  // asicseer-pool and ckpool have no SSL/TLS library — they speak plain
  // HTTP JSON-RPC only. A stunnel SubContainer accepts plaintext on 8334
  // and forwards to BCHD's native TLS RPC on 127.0.0.1:8332 internally.
  // TLS is never absent on the BCHD side; it just terminates at stunnel.
  // When upstream gains native TLS support this daemon and interface are
  // removed in a single commit — no changes needed in the miner packages.
  const rpcPlaintextMulti = sdk.MultiHost.of(effects, rpcPlaintextHostId)
  const rpcPlaintextOrigin = await rpcPlaintextMulti.bindPort(rpcPlaintextPort, {
    protocol: null,
    preferredExternalPort: rpcPlaintextPort,
    addSsl: null,
    secure: { ssl: false },
  })
  const rpcPlaintext = sdk.createInterface(effects, {
    name: 'RPC Plaintext Proxy',
    id: rpcPlaintextInterfaceId,
    description:
      'Plaintext JSON-RPC for miners (asicseer-pool, ckpool) that lack TLS support',
    type: 'api',
    masked: false,
    schemeOverride: { ssl: 'http', noSsl: 'http' },
    username: null,
    path: '',
    query: {},
  })
  receipts.push(await rpcPlaintextOrigin.export([rpcPlaintext]))

  return receipts
})
